# Generated by Django 4.2.1 on 2025-05-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
